"""Qualify installed old/current wheels against isolated native type stores.

Run the orchestrator with explicit venv interpreters. Workers use -I and prove the
import comes from that environment, not this checkout. Keeps artifacts/receipts;
never installs packages, deletes a database or accepts an existing output root.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
from importlib.metadata import version
import json
from pathlib import Path
import subprocess
import sys
from zipfile import ZipFile


def snapshot(root):
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file()}


def temporal_values():
    from okto_grafx import DateValue, LocalTimeValue, TimeValue, LocalDateTimeValue, DateTimeValue, DurationValue
    return (DateValue(-999999999, 2, 28), LocalTimeValue(86399999999999),
            TimeValue(LocalTimeValue(1), -1234),
            LocalDateTimeValue(DateValue(999999999, 12, 31), LocalTimeValue(999999999)),
            DateTimeValue.from_epoch_parts(-1, 999999999, offset_seconds=1234, zone="Future/Recorded"),
            DurationValue(2**63-1, -3, -1, 999999999))


def capability_bit(capability):
    if capability == "type_bundle":
        return (1 << 20) | (1 << 23) | (1 << 26) | (1 << 27)
    return 1 << {"temporal": 23, "graph_namespaces": 24, "vector_owners": 25,
                 "decimal": 26, "typed_collections": 27, "node_labels": 28}[capability]


def write_label_fixture(tx):
    """Exercise membership on one existing identity plus explicit empty/new nodes."""
    tx.execute("MATCH(n:N {id:1}) SET n:LabelA:LabelB REMOVE n:N")
    tx.execute("CREATE(:N:LabelB {id:2}), (n:N {id:3}) REMOVE n:N")


def label_fixture_rows():
    """Independent logical oracle, not decoded from candidate data."""
    return ((1, ("LabelA", "LabelB")), (2, ("LabelB", "N")), (3, ()))


def typed_fixture(capability):
    """Explicit independent values/types, not values inferred from recovered rows."""
    from okto_grafx import DecimalValue, StoredType
    if capability == "decimal":
        return (("amount", "DECIMAL(38,19)", DecimalValue(-(10**38-1), 38, 19)),)
    base = (("xs", "LIST<INT64 NOT NULL>", (-(2**63), 2**63-1)),
            ("pair", "ARRAY<STRING,2>", ("α", None)),
            ("empty", "STRUCT<>", {}), ("zero", "ARRAY<INT64,0>", ()))
    if capability == "typed_collections":
        return base
    assert capability == "type_bundle", capability
    kinds = ("DATE", "LOCALTIME", "TIME", "LOCALDATETIME", "DATETIME", "DURATION")
    mixed = StoredType("STRUCT", fields=(
        ("amounts", StoredType("MAP", element=StoredType("DECIMAL", precision=12, scale=4))),
        ("days", StoredType("LIST", element=StoredType("DATE"))),
        ("meta", StoredType("MAP", element=StoredType("ANY")))))
    return (typed_fixture("decimal") + base
            + tuple((f"t{i}", kind, value) for i, (kind, value) in enumerate(zip(kinds, temporal_values())))
            + (("nested", mixed.describe(), {"amounts": {"x": DecimalValue(12500,12,4), "null": None},
                  "days": (temporal_values()[0], None), "meta": {"mixed": (1,"1",False),
                  "keys": {(1,2): b"abc", None: DecimalValue(0,38,38)}}}),))


def package_snapshot(root):
    """Compare actual package resources, excluding only interpreter-generated bytecode."""
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file()
            and "__pycache__" not in p.parts and p.suffix not in (".pyc", ".pyo")}


def wheel_snapshot(path):
    with ZipFile(path) as wheel:
        return {name.removeprefix("okto_grafx/"): hashlib.sha256(wheel.read(name)).hexdigest()
                for name in wheel.namelist() if name.startswith("okto_grafx/") and not name.endswith("/")}


def prove_package(info, wheel, source_root=None):
    expected = wheel_snapshot(wheel)
    assert expected and info["files"] == expected, "Installed package differs from its wheel"
    if source_root is not None:
        assert package_snapshot(source_root / "src" / "okto_grafx") == expected, "Candidate wheel differs from checkout"
    return {"path": str(wheel), "sha256": hashlib.sha256(wheel.read_bytes()).hexdigest(),
            "package_files": len(expected), "source_checked": source_root is not None}


def worker(action, path, mode, profile="pure", capability="temporal"):
    import okto_grafx
    from okto_grafx import connect
    from okto_grafx.errors import GrafxError

    origin = Path(okto_grafx.__file__).resolve()
    assert origin.is_relative_to(Path(sys.prefix).resolve()), (origin, sys.prefix)
    result = {"version": version("okto-grafx"), "origin": str(origin), "action": action, "profile": profile}
    options = ({"codec": "pure", "vector_math": "pure", "checksum": "pure"} if profile == "pure" else
               {"codec": "numpy", "vector_math": "numpy", "checksum": "native"})
    if action == "info":
        from okto_grafx.domain.model import catalog
        result["known_capability_bits"] = catalog._KNOWN_CAPABILITY_BITS
        result["files"] = package_snapshot(origin.parent)
    elif action == "seed_plain":
        with connect(path, **options) as db:
            with db.begin() as tx:
                tx.execute("CREATE NODE TABLE N(id INT64,PRIMARY KEY(id))")
                tx.execute("CREATE(:N {id:1})")
                if capability == "vector_owners":
                    tx.execute("CREATE VECTOR SPACE s {dimension:2,metric:'cosine'}")
                    tx.execute("CREATE NODE TABLE T_a(id INT64,v VECTOR(s),PRIMARY KEY(id))")
                    tx.execute("CREATE(:T_a {id:11,v:$v})", {"v":[1.0,0.0]})
            db.ensure_identity_indexes()
            db.checkpoint()
    elif action == "plain":
        with connect(path, read_only=mode == "read", **options) as db:
            assert db.execute("MATCH(n:N) RETURN n.id").rows == ((1,),)
            if mode == "write":
                with db.begin() as tx:
                    tx.execute("MATCH(n:N {id:1}) SET n.id=1")
                db.checkpoint()
            assert not db.verify("all").findings
    elif action in ("activate", "pending"):
        from okto_grafx.engine.txn_manager import TransactionManager
        import os

        values = temporal_values() if capability == "temporal" else ()
        kinds = ("DATE", "LOCALTIME", "TIME", "LOCALDATETIME", "DATETIME", "DURATION")
        with connect(path, **options) as db:
            active = None
            if action == "pending":
                original = TransactionManager._apply_images

                def stop(manager, images):
                    if active is not None and active._context.state.value == "committed":
                        os._exit(73)  # Durable COMMIT proved; no pages applied yet.
                    return original(manager, images)

                TransactionManager._apply_images = stop
            with db.begin() as tx:
                active = tx
                if capability in ("decimal", "typed_collections", "type_bundle"):
                    fixture = typed_fixture(capability)
                    tx.execute("CREATE NODE TABLE Typed(id INT64," + ",".join(f"{name} {kind}" for name, kind, _ in fixture) + ",PRIMARY KEY(id))")
                    tx.execute("CREATE(:Typed {id:1," + ",".join(f"{name}:${name}" for name, _, _ in fixture) + "})",
                               {name: value for name, _, value in fixture})
                    tx.execute("CREATE(:Typed {id:2})")
                elif capability == "node_labels":
                    write_label_fixture(tx)
                elif capability == "vector_owners":
                    assert db.vectors.index("s").name == "vector_T_a_s"
                    tx.execute("CREATE VECTOR SPACE a_s {dimension:2,metric:'cosine'}")
                    tx.execute("CREATE NODE TABLE T(id INT64,v VECTOR(a_s),PRIMARY KEY(id))")
                    tx.execute("CREATE(:T {id:22,v:$v})", {"v":[0.0,1.0]})
                elif capability == "graph_namespaces":
                    tx.execute("CREATE NODE TABLE R(id INT64,body STRING,PRIMARY KEY(id))")
                    tx.execute("CREATE REL TABLE R(FROM R TO R,body STRING)")
                    tx.execute("CREATE(n:R {id:7,body:'node'})-[:R {body:'edge'}]->(n)")
                else:
                    tx.execute("CREATE NODE TABLE Temporal(id INT64," + ",".join(f"v{i} {kind}" for i, kind in enumerate(kinds)) + ",PRIMARY KEY(id))")
                    tx.execute("CREATE(:Temporal {id:1," + ",".join(f"v{i}:$v{i}" for i in range(6)) + "})",
                               {f"v{i}": value for i, value in enumerate(values)})
            if action == "pending":
                TransactionManager._apply_images = original
                raise AssertionError("Pending-WAL cut not reached")
            result["capabilities"] = db._catalog.catalog.required_capabilities()
            db.checkpoint()
    elif action == "refuse":
        try:
            with connect(path, read_only=mode == "read", **options) as db:
                db.execute("MATCH(n:N) RETURN n.id")
        except GrafxError as exc:
            result["refusal"] = {"type": type(exc).__name__, "code": exc.code,
                                 "message": str(exc), "details": dict(exc.details)}
        else:
            raise AssertionError("Old wheel accepted the temporal store")
    elif action == "live_refuse":
        with connect(path, read_only=mode == "read", **options) as db:
            print(json.dumps({"ready": True, "origin": str(origin)}), flush=True)
            assert sys.stdin.readline().strip() == "go"
            try:
                if mode == "read":
                    db.execute("MATCH(n:N) RETURN n.id")
                else:
                    with db.begin() as tx:
                        tx.execute("CREATE(:N {id:2})")
            except GrafxError as exc:
                result["refusal"] = {"type": type(exc).__name__, "code": exc.code,
                                     "message": str(exc), "details": dict(exc.details)}
            else:
                raise AssertionError("Live old handle accepted the temporal store")
    elif action == "verify_temporal":
        from okto_grafx.domain.model.temporal_interchange import temporal_json_value
        with connect(path, **options) as db:
            if capability in ("decimal", "typed_collections", "type_bundle"):
                fixture = typed_fixture(capability)
                rows = db.execute("MATCH(n:Typed) RETURN n.id," + ",".join(f"n.{name}" for name, _, _ in fixture) + " ORDER BY n.id").rows
                assert rows == ((1, *(value for _, _, value in fixture)), (2, *(None for _ in fixture))), rows
                from okto_grafx.domain.model.value import encode_value
                result["values"] = [encode_value(row).hex() for row in rows]
                result["declarations"] = [[name, kind] for name, kind, _ in fixture]
                required = db._catalog.catalog.required_capabilities()
                result["capabilities"] = required
            elif capability == "node_labels":
                rows = db.execute("MATCH(n) RETURN n.id,labels(n) ORDER BY n.id").rows
                assert rows == label_fixture_rows(), rows
                result["values"] = list(rows)
                result["capabilities"] = db._catalog.catalog.required_capabilities()
            elif capability == "vector_owners":
                assert db.vectors.index("s").name == "vector_T_a_s"
                assert db.vectors.index("a_s").name.startswith("_grafx_vec_")
                assert db.catalog.catalog.table("T_a").vector_identity_names is False
                assert db.catalog.catalog.table("T").vector_identity_names is True
                with db.begin("read") as tx:
                    first = db.search_vectors(tx, table="T_a", space="s", query=[1.0,0.0], k=1)
                    second = db.search_vectors(tx, table="T", space="a_s", query=[1.0,0.0], k=1)
                    assert len(first.hits) == len(second.hits) == 1
                    assert first.hits[0].score == 1.0 and second.hits[0].score == 0.0
                result["values"] = [db.execute("MATCH(n:T_a) RETURN n.id").rows[0][0],
                                    db.execute("MATCH(n:T) RETURN n.id").rows[0][0],
                                    first.hits[0].score, second.hits[0].score]
            elif capability == "graph_namespaces":
                rows = db.execute("MATCH(n:R)-[r:R]->(m:R) RETURN n.id,n.body,r.body,m.id").rows
                assert rows == ((7,"node","edge",7),), rows
                assert db.catalog.catalog.table("R",kind="node").table_id != db.catalog.catalog.table("R",kind="rel").table_id
                result["values"] = list(rows[0])
            else:
                rows = db.execute("MATCH(n:Temporal) RETURN " + ",".join(f"n.v{i}" for i in range(6))).rows
                assert rows == (temporal_values(),), rows
                result["values"] = [temporal_json_value(value) for value in rows[0]]
            assert not db.verify("all").findings
            db.checkpoint()
    else:
        raise AssertionError(action)
    print(json.dumps(result, sort_keys=True))


def execute(python, action, path, mode="write", expected=0, profile="pure", capability="temporal"):
    completed = subprocess.run([str(python), "-I", str(Path(__file__).resolve()),
                               "--worker", action, str(path), mode, profile, capability],
                              capture_output=True, text=True, timeout=60)
    if completed.returncode != expected:
        raise AssertionError(f"{action}: {completed.returncode}\n{completed.stdout}\n{completed.stderr}")
    return json.loads(completed.stdout) if expected == 0 else {"crash_exit": expected}


def validate_refusal(refusal, state, mode, *, capability="temporal", known_bits=0):
    expected = capability_bit(capability) & ~known_bits
    assert expected, "Selected binary is not an old reader of this capability"
    observed = refusal["refusal"]
    if state == "pending" and mode == "read":
        assert observed["code"] == "unsupported_operation", observed
        assert observed["details"]["field"] == "read_only_consistency", observed
    else:
        assert observed["code"] == "schema_version_mismatch", observed
        assert observed["details"]["unsupported"] == expected, observed


def live_probe(old, current, path, mode, profile, capability="temporal"):
    command = [str(old), "-I", str(Path(__file__).resolve()), "--worker", "live_refuse", str(path), mode, "pure", capability]
    child = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    try:
        with ThreadPoolExecutor(max_workers=1) as pool:
            ready = pool.submit(child.stdout.readline)
            try:
                assert json.loads(ready.result(timeout=30))["ready"]
            except BaseException:
                child.kill()
                raise
        activation = execute(current, "activate", path, profile=profile, capability=capability)
        before = snapshot(path)
        out, err = child.communicate(input="go\n", timeout=60)
        assert child.returncode == 0, (out, err)
        refusal = json.loads(out)
        after = snapshot(path)
        return activation, refusal, before, after
    finally:
        if child.poll() is None:
            child.kill()
        child.communicate()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--current-python", type=Path, required=True)
    parser.add_argument("--old-python", type=Path, action="append", required=True)
    parser.add_argument("--current-wheel", type=Path)
    parser.add_argument("--old-wheel", type=Path, action="append")
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--profile", choices=("pure", "accelerated"), default="pure")
    parser.add_argument("--capability", choices=("temporal", "graph_namespaces", "vector_owners", "decimal", "typed_collections", "type_bundle", "node_labels"), default="temporal")
    args = parser.parse_args()
    root = args.output.resolve()
    root.mkdir(parents=True, exist_ok=False)
    current = args.current_python.resolve(strict=True)
    olds = [p.resolve(strict=True) for p in args.old_python]
    report = {"current": execute(current, "info", root), "profile": args.profile, "capability": args.capability,
              "old": [], "cases": [], "passed": False}
    required_bit = capability_bit(args.capability)
    assert report["current"]["known_capability_bits"] & required_bit == required_bit
    try:
        if args.current_wheel is not None:
            report["current"]["wheel"] = prove_package(report["current"], args.current_wheel.resolve(strict=True), args.source_root)
        if args.old_wheel is not None:
            assert len(args.old_wheel) == len(olds), "Every old interpreter needs its own wheel"
        for number, old in enumerate(olds):
            report["old"].append(execute(old, "info", root))
            old_bits = report["old"][-1]["known_capability_bits"]
            assert old_bits & required_bit != required_bit
            if args.old_wheel is not None:
                report["old"][-1]["wheel"] = prove_package(report["old"][-1], args.old_wheel[number].resolve(strict=True))
            for state in ("materialized", "pending", "live"):
                for mode in ("read", "write"):
                    path = root / f"old-{number}-{state}-{mode}"
                    execute(old, "seed_plain", path, capability=args.capability)
                    execute(current, "plain", path, "write", profile=args.profile)
                    execute(old, "plain", path, "read")
                    if state == "live":
                        activation, refusal, before, after = live_probe(old, current, path, mode, args.profile, args.capability)
                    else:
                        activation = execute(current, "activate" if state == "materialized" else "pending", path,
                                             expected=0 if state == "materialized" else 73, profile=args.profile, capability=args.capability)
                        before = snapshot(path)
                        refusal = execute(old, "refuse", path, mode)
                        after = snapshot(path)
                    changed = sorted(name for name in before.keys() | after.keys() if before.get(name) != after.get(name))
                    case = {"old": number, "state": state, "mode": mode, "activation": activation,
                            "refusal": refusal, "changed_files": changed, "before": before, "after": after}
                    report["cases"].append(case)
                    validate_refusal(refusal, state, mode, capability=args.capability, known_bits=old_bits)
                    # Start with an exact all-file audit. No preemptive exclusions
                    # hide unexpected coordination, WAL or data mutations.
                    assert not changed, changed
                    case["recovered"] = execute(current, "verify_temporal", path, capability=args.capability)
                    assert execute(current, "verify_temporal", path, capability=args.capability)["values"] == case["recovered"]["values"]
                    print(json.dumps({"old": number, "state": state, "mode": mode, "passed": True}), flush=True)
        report["passed"] = True
    finally:
        (root / "report.json").write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({"passed": True, "cases": len(report["cases"]), "report": str(root / "report.json")}))


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--worker":
        worker(*sys.argv[2:])
    else:
        main()
