"""The query language of Okto Grafx: lexer, parser, syntax, meaning and plan (D3).

The dialect is openCypher as the Kuzu engine spells it, and that choice is the compatibility
promise this project makes to anyone migrating off the reference engine -- so it is a fixed
target rather than a design space. What lives here is only the language and the plan: reading
text into a statement, deciding what the statement means, and choosing the operator tree that
answers it. Nothing in this package opens a page, holds a snapshot or touches a port; the engine
module :mod:`okto_grafx.engine.query_engine` does that, and it is the only thing that does.

Read in this order:

* :mod:`okto_grafx.domain.query.limits` -- every bound, and why an unbounded one is a defect;
* :mod:`okto_grafx.domain.query.lexer` -- text into tokens, and the four hostile shapes it names;
* :mod:`okto_grafx.domain.query.parser` -- tokens into a statement, with a bounded descent;
* :mod:`okto_grafx.domain.query.analysis` -- what a statement means, with no catalog in reach;
* :mod:`okto_grafx.domain.query.plan` -- the operator tree and the two shapes it refuses;
* :mod:`okto_grafx.domain.query.planner` -- the statement bound to a catalog.
"""

from __future__ import annotations

from okto_grafx.domain.query.analysis import (
    ENTITY_NODE,
    ENTITY_RELATIONSHIP,
    Aggregation,
    Binding,
    QueryAnalysis,
    SimilarityUse,
    analyze,
    contains_aggregate,
    is_aggregate,
)
from okto_grafx.domain.query.ast import (
    BinaryOperation,
    CaseAlternative,
    CaseExpression,
    ColumnSpec,
    CreateClause,
    CreateNodeTableStatement,
    CreateRelTableStatement,
    CreateVectorSpaceStatement,
    DeleteClause,
    Direction,
    Expression,
    FunctionCall,
    ListExpression,
    Literal,
    MapEntry,
    MapExpression,
    MatchClause,
    MergeClause,
    NamedArgument,
    NodePattern,
    NullCheck,
    Parameter,
    PatternPath,
    Property,
    Query,
    RelationshipPattern,
    ReturnClause,
    ReturnItem,
    SetClause,
    SetItem,
    SortItem,
    Statement,
    Subscript,
    UnaryOperation,
    UpdatingClause,
    UnionQuery,
    UnwindClause,
    Variable,
    WithClause,
    free_variables,
    walk,
)
from okto_grafx.domain.query.lexer import tokenize
from okto_grafx.domain.query.limits import (
    DEFAULT_MAX_QUERY_VALUE_CHARACTERS,
    MAX_CLAUSES,
    MAX_COLUMN_DEFINITIONS,
    MAX_EXPRESSION_DEPTH,
    MAX_LIST_ELEMENTS,
    MAX_MAP_ENTRIES,
    MAX_NAME_CHARACTERS,
    MAX_NUMBER_CHARACTERS,
    MAX_PARAMETERS,
    MAX_PATTERN_ELEMENTS,
    MAX_PATTERNS_PER_CLAUSE,
    MAX_PROJECTION_ITEMS,
    MAX_QUERY_CHARACTERS,
    MAX_QUERY_VALUE_CHARACTERS,
    MAX_RENDERED_QUERY_CHARACTERS,
    MAX_SORT_KEYS,
    MAX_STRING_CHARACTERS,
    MAX_TOKENS,
    MAX_TRAVERSAL_HOPS,
)
from okto_grafx.domain.query.parser import COLUMN_TYPE_NAMES, VECTOR_TYPE_NAME, parse
from okto_grafx.domain.query.plan import (
    MAX_PLAN_DEPTH,
    AggregateRows,
    AllNodesScan,
    CreatedNode,
    CreatedRelationship,
    CreateNodeTable,
    CreateRelationships,
    CreateRelTable,
    CreateVectorSpace,
    DeleteEntities,
    DistinctRows,
    EagerRows,
    FilterRows,
    IndexSeek,
    LimitRows,
    MergePattern,
    NodeScan,
    PlanNode,
    ProduceResults,
    ProjectRows,
    PropertyAssignment,
    SetProperties,
    SingleRow,
    SkipRows,
    SortRows,
    TraverseRelationship,
    UnionRows,
    VectorSearch,
    plan_nodes,
    validate_plan,
)
from okto_grafx.domain.query.planner import (
    ANONYMOUS_VARIABLE_PREFIX,
    COLUMN_VALUE_TYPES,
    SCORE_COLUMN,
    THRESHOLD_OPERATORS,
    PlannedQuery,
    build_plan,
    conjuncts_of,
)
from okto_grafx.domain.query.tokens import (
    AGGREGATE_FUNCTIONS,
    COALESCE_FUNCTION,
    KEYWORDS,
    LABEL_FUNCTION,
    SIMILARITY_FUNCTION,
    SIMILARITY_SCORE_FUNCTION,
    SIZE_FUNCTION,
    STRING_SPLIT_FUNCTION,
    SYMBOLS,
    TIMESTAMP_FUNCTION,
    Token,
    TokenKind,
)

__all__ = [
    "AGGREGATE_FUNCTIONS",
    "ANONYMOUS_VARIABLE_PREFIX",
    "COLUMN_TYPE_NAMES",
    "COLUMN_VALUE_TYPES",
    "COALESCE_FUNCTION",
    "DEFAULT_MAX_QUERY_VALUE_CHARACTERS",
    "ENTITY_NODE",
    "ENTITY_RELATIONSHIP",
    "KEYWORDS",
    "LABEL_FUNCTION",
    "MAX_CLAUSES",
    "MAX_COLUMN_DEFINITIONS",
    "MAX_EXPRESSION_DEPTH",
    "MAX_LIST_ELEMENTS",
    "MAX_MAP_ENTRIES",
    "MAX_NAME_CHARACTERS",
    "MAX_NUMBER_CHARACTERS",
    "MAX_PARAMETERS",
    "MAX_PATTERNS_PER_CLAUSE",
    "MAX_PATTERN_ELEMENTS",
    "MAX_PLAN_DEPTH",
    "MAX_PROJECTION_ITEMS",
    "MAX_QUERY_CHARACTERS",
    "MAX_QUERY_VALUE_CHARACTERS",
    "MAX_RENDERED_QUERY_CHARACTERS",
    "MAX_SORT_KEYS",
    "MAX_STRING_CHARACTERS",
    "MAX_TOKENS",
    "MAX_TRAVERSAL_HOPS",
    "SCORE_COLUMN",
    "SIZE_FUNCTION",
    "SIMILARITY_FUNCTION",
    "SIMILARITY_SCORE_FUNCTION",
    "STRING_SPLIT_FUNCTION",
    "SYMBOLS",
    "TIMESTAMP_FUNCTION",
    "THRESHOLD_OPERATORS",
    "VECTOR_TYPE_NAME",
    "AggregateRows",
    "AllNodesScan",
    "Aggregation",
    "BinaryOperation",
    "Binding",
    "CaseAlternative",
    "CaseExpression",
    "ColumnSpec",
    "CreateClause",
    "CreateNodeTable",
    "CreateNodeTableStatement",
    "CreateRelTable",
    "CreateRelTableStatement",
    "CreateRelationships",
    "CreateVectorSpace",
    "CreateVectorSpaceStatement",
    "CreatedNode",
    "CreatedRelationship",
    "DeleteClause",
    "DeleteEntities",
    "Direction",
    "DistinctRows",
    "EagerRows",
    "Expression",
    "FilterRows",
    "FunctionCall",
    "IndexSeek",
    "LimitRows",
    "ListExpression",
    "Literal",
    "MapEntry",
    "MapExpression",
    "MatchClause",
    "MergeClause",
    "MergePattern",
    "NamedArgument",
    "NodePattern",
    "NodeScan",
    "NullCheck",
    "Parameter",
    "PatternPath",
    "PlanNode",
    "PlannedQuery",
    "ProduceResults",
    "ProjectRows",
    "Property",
    "PropertyAssignment",
    "Query",
    "QueryAnalysis",
    "RelationshipPattern",
    "ReturnClause",
    "ReturnItem",
    "SetClause",
    "SetItem",
    "SetProperties",
    "SimilarityUse",
    "SingleRow",
    "SkipRows",
    "SortItem",
    "SortRows",
    "Statement",
    "Subscript",
    "Token",
    "TokenKind",
    "TraverseRelationship",
    "UnionQuery",
    "UnionRows",
    "UnaryOperation",
    "UnwindClause",
    "UpdatingClause",
    "Variable",
    "VectorSearch",
    "WithClause",
    "analyze",
    "build_plan",
    "conjuncts_of",
    "contains_aggregate",
    "free_variables",
    "is_aggregate",
    "parse",
    "plan_nodes",
    "tokenize",
    "validate_plan",
    "walk",
]
